export const LOCATIONS = [
  "Bloco A - Sala de Aula 101",
  "Bloco B - Laboratório de Informática",
  "Bloco C - Laboratório 101",
  "Bloco D - Sala de Seminários",
  "Bloco E - Galeria de Arte",
  "Bloco F - Estúdio de Música",
  "Auditório Principal - Campus",
  "Quadra do Campus",
  "Espaço Principal do Campus",
  "Laboratório de Enfermagem",
  "Laboratório de Medicina",
  "Laboratório de Farmácia",
];

export const events = [
  // Ciência da Computação
  {
    id: 1,
    title: "Hackathon de IA e Machine Learning",
    description: "Competição de desenvolvimento com foco em inteligência artificial. Equipes competem por prêmios e reconhecimento.",
    date: "15 de Junho",
    time: "14:00",
    location: "Bloco B - Laboratório de Informática",
    category: "Ciência da Computação",
    course: "Ciência da Computação",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop&q=80",
    participants: 156,
  },
  {
    id: 2,
    title: "Palestra: Desenvolvimento Web Moderno",
    description: "Especialista em web development apresenta as últimas tendências e ferramentas do mercado.",
    date: "18 de Junho",
    time: "16:00",
    location: "Bloco A - Sala de Aula 101",
    category: "Ciência da Computação",
    course: "Ciência da Computação",
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&h=400&fit=crop&q=80",
    participants: 89,
  },
  {
    id: 3,
    title: "Workshop: Desenvolvimento de Apps Mobile",
    description: "Aprenda a criar aplicativos para iOS e Android com as melhores práticas da indústria.",
    date: "20 de Junho",
    time: "15:00",
    location: "Bloco B - Laboratório de Informática",
    category: "Ciência da Computação",
    course: "Ciência da Computação",
    image: "/images/workshop-apps.jpg",
    participants: 67,
  },

  // Engenharia Civil
  {
    id: 4,
    title: "Visita Técnica: Obra em Construção",
    description: "Conhecer na prática os processos de construção civil e tecnologias inovadoras.",
    date: "16 de Junho",
    time: "09:00",
    location: "Espaço Principal do Campus",
    category: "Engenharia Civil",
    course: "Engenharia Civil",
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?w=600&h=400&fit=crop&q=80",
    participants: 45,
  },
  {
    id: 5,
    title: "Seminário: Estruturas Sustentáveis",
    description: "Discutir soluções inovadoras para construção eco-sustentável e eficiente energeticamente.",
    date: "22 de Junho",
    time: "14:00",
    location: "Bloco C - Auditório Principal",
    category: "Engenharia Civil",
    course: "Engenharia Civil",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=600&h=400&fit=crop&q=80",
    participants: 78,
  },

  // Engenharia Elétrica
  {
    id: 6,
    title: "Workshop: Instalações Elétricas Modernas",
    description: "Aprenda sobre sistemas elétricos contemporâneos e segurança em instalações.",
    date: "17 de Junho",
    time: "13:00",
    location: "Laboratório de Física",
    category: "Engenharia Elétrica",
    course: "Engenharia Elétrica",
    image: "images/workshop-eletrica.jpg",
    participants: 52,
  },
  {
    id: 7,
    title: "Palestra: Energia Renovável",
    description: "Especialista apresenta soluções de energia renovável e painéis solares.",
    date: "23 de Junho",
    time: "15:00",
    location: "Bloco D - Sala de Seminários",
    category: "Engenharia Elétrica",
    course: "Engenharia Elétrica",
    image: "https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=600&h=400&fit=crop&q=80",
    participants: 98,
  },

  // Medicina
  {
    id: 8,
    title: "Palestra: Avanços em Medicina Regenerativa",
    description: "Conheça as últimas descobertas em terapia celular e medicina regenerativa.",
    date: "19 de Junho",
    time: "10:00",
    location: "Bloco C - Auditório Principal",
    category: "Medicina",
    course: "Medicina",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&h=400&fit=crop&q=80",
    participants: 234,
  },
  {
    id: 9,
    title: "Seminário: Ética Médica Contemporânea",
    description: "Discussão sobre dilemas éticos na prática médica moderna.",
    date: "24 de Junho",
    time: "14:00",
    location: "Bloco A - Sala de Aula 101",
    category: "Medicina",
    course: "Medicina",
    image: "images/seminario-etica-medica.png",
    participants: 156,
  },

  // Enfermagem
  {
    id: 10,
    title: "Workshop: Primeiros Socorros Avançados",
    description: "Treinamento prático de técnicas avançadas de primeiros socorros.",
    date: "21 de Junho",
    time: "09:00",
    location: "Laboratório de Biologia",
    category: "Enfermagem",
    course: "Enfermagem",
    image: "images/workshop-primeiros-socorros.jpg",
    participants: 89,
  },

  // Psicologia
  {
    id: 11,
    title: "Palestra: Saúde Mental em Tempos de Crise",
    description: "Abordagem prática sobre cuidados psicológicos e bem-estar emocional.",
    date: "18 de Junho",
    time: "11:00",
    location: "Bloco D - Sala de Seminários",
    category: "Psicologia",
    course: "Psicologia",
    image: "images/palestra-saude-mental.jpg",
    participants: 112,
  },
  {
    id: 12,
    title: "Oficina: Mindfulness e Meditação",
    description: "Práticas de atenção plena e meditação para bem-estar geral.",
    date: "25 de Junho",
    time: "15:00",
    location: "Espaço Principal do Campus",
    category: "Psicologia",
    course: "Psicologia",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=600&h=400&fit=crop&q=80",
    participants: 67,
  },

  // Direito
  {
    id: 13,
    title: "Seminário: Direito Digital e Privacidade",
    description: "Análise das leis de proteção de dados e direitos digitais.",
    date: "20 de Junho",
    time: "16:00",
    location: "Bloco A - Sala de Aula 101",
    category: "Direito",
    course: "Direito",
    image: "images/seminario-direito-digital.jpg",
    participants: 78,
  },
  {
    id: 14,
    title: "Palestra: Direitos Humanos e Justiça Social",
    description: "Discussão sobre direitos fundamentais e justiça social contemporânea.",
    date: "26 de Junho",
    time: "14:00",
    location: "Bloco C - Auditório Principal",
    category: "Direito",
    course: "Direito",
    image: "images/palestra-direitos-humanos.jpg",
    participants: 145,
  },

  // Pedagogia
  {
    id: 15,
    title: "Workshop: Metodologias Ativas de Aprendizado",
    description: "Estratégias inovadoras para engajar alunos e potencializar aprendizado.",
    date: "17 de Junho",
    time: "14:00",
    location: "Bloco B - Laboratório de Informática",
    category: "Pedagogia",
    course: "Pedagogia",
    image: "images/workshop-metodologias-ativas.jpg",
    participants: 93,
  },
  {
    id: 16,
    title: "Palestra: Educação Inclusiva",
    description: "Abordagens para educação inclusiva e acessível para todos.",
    date: "23 de Junho",
    time: "10:00",
    location: "Bloco D - Sala de Seminários",
    category: "Pedagogia",
    course: "Pedagogia",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&h=400&fit=crop&q=80",
    participants: 87,
  },

  // Publicidade e Propaganda
  {
    id: 17,
    title: "Palestra: Marketing Digital e Redes Sociais",
    description: "Estratégias de marketing digital e gerenciamento de redes sociais.",
    date: "19 de Junho",
    time: "15:00",
    location: "Bloco A - Sala de Aula 101",
    category: "Publicidade e Propaganda",
    course: "Publicidade e Propaganda",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop&q=80",
    participants: 134,
  },
  {
    id: 18,
    title: "Workshop: Design Criativo e Branding",
    description: "Técnicas de design gráfico e desenvolvimento de identidade visual.",
    date: "21 de Junho",
    time: "16:00",
    location: "Bloco E - Galeria de Arte",
    category: "Publicidade e Propaganda",
    course: "Publicidade e Propaganda",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&h=400&fit=crop&q=80",
    participants: 67,
  },

  // Agronomia
  {
    id: 19,
    title: "Seminário: Agricultura Sustentável",
    description: "Práticas modernas de agricultura ecológica e sustentável.",
    date: "22 de Junho",
    time: "09:00",
    location: "Espaço Principal do Campus",
    category: "Agronomia",
    course: "Agronomia",
    image: "images/seminario-agricultura.jpg",
    participants: 45,
  },
  {
    id: 20,
    title: "Visita Técnica: Plantação Orgânica",
    description: "Conhecer na prática os processos de cultivo orgânico.",
    date: "27 de Junho",
    time: "08:00",
    location: "Espaço Principal do Campus",
    category: "Agronomia",
    course: "Agronomia",
    image: "images/visita-tecnica.jpg",
    participants: 38,
  },

  // Design Gráfico
  {
    id: 21,
    title: "Workshop: Motion Graphics e Animação",
    description: "Criação de animações e gráficos em movimento para multimídia.",
    date: "20 de Junho",
    time: "14:00",
    location: "Bloco E - Galeria de Arte",
    category: "Design Gráfico",
    course: "Design Gráfico",
    image: "images/workshop-motion.jpg",
    participants: 56,
  },

  // Artes Visuais
  {
    id: 22,
    title: "Mostra de Artes Visuais",
    description: "Exposição com trabalhos de alunos de pintura, escultura e artes digitais.",
    date: "25 de Junho",
    time: "10:00",
    location: "Bloco E - Galeria de Arte",
    category: "Artes Visuais",
    course: "Artes Visuais",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crop&q=80",
    participants: 123,
  },

  // Música
  {
    id: 23,
    title: "Recital de Música Clássica",
    description: "Apresentação de alunos de música realizando peças clássicas.",
    date: "24 de Junho",
    time: "19:00",
    location: "Bloco F - Estúdio de Música",
    category: "Música",
    course: "Música",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&h=400&fit=crop&q=80",
    participants: 89,
  },
  {
    id: 24,
    title: "Jam Session: Músicas Contemporâneas",
    description: "Sessão aberta de improvisação com músicas atuais.",
    date: "29 de Junho",
    time: "20:00",
    location: "Auditório Principal - Campus",
    category: "Música",
    course: "Música",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=600&h=400&fit=crop&q=80",
    participants: 156,
  },

  // Artes Cênicas Geral
  {
    id: 25,
    title: "Festival de Teatro Experimental",
    description: "Apresentações de peças teatrais criativas e inovadoras.",
    date: "21 de Junho",
    time: "19:00",
    location: "Bloco C - Auditório Principal",
    category: "Artes Cênicas",
    course: "Teatro",
    image: "images/festival-teatro-experimental.jpg",
    participants: 245,
  },
  {
    id: 26,
    title: "Oficina de Dança Contemporânea",
    description: "Aulas práticas de dança contemporânea com professor convidado.",
    date: "28 de Junho",
    time: "17:00",
    location: "Quadra do Campus",
    category: "Dança",
    course: "Artes Cênicas",
    image: "images/oficina-danca.jpg",
    participants: 78,
  },

  // Geral
  {
    id: 27,
    title: "Feira de Oportunidades Acadêmicas",
    description: "Apresentação de programas de bolsas, intercâmbio e pesquisa.",
    date: "30 de Junho",
    time: "10:00",
    location: "Espaço Principal do Campus",
    category: "Geral",
    course: "Multidisciplinar",
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop&q=80",
    participants: 523,
  },
];
