export const groups = [
  // Artes e Cultura
  {
    id: 1,
    name: "Clube de Fotografia",
    category: "Artes",
    description: "Grupo dedicado à fotografia, compartilhando técnicas, experiências e saídas fotográficas.",
    members: 347,
    image: "https://images.unsplash.com/photo-1606986628025-35d57e735ae0?w=400&h=300&fit=crop",
    course: "Design Gráfico",
  },
  {
    id: 2,
    name: "Banda Universitária",
    category: "Música",
    description: "Banda oficial da universidade, apresentando-se em eventos culturais e festivais.",
    members: 89,
    image: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&h=300&fit=crop",
    course: "Música",
  },
  {
    id: 3,
    name: "Teatro Experimental",
    category: "Artes Cênicas",
    description: "Grupo de teatro focado em experimentações e novas formas de expressão artística.",
    members: 156,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Teatro",
  },
  {
    id: 4,
    name: "Grupo de Dança",
    category: "Dança",
    description: "Apresentações de dança clássica, contemporânea e outros estilos.",
    members: 203,
    image: "https://images.unsplash.com/photo-1508700115892-5e266fcd6bac?w=400&h=300&fit=crop",
    course: "Artes Cênicas",
  },
  {
    id: 5,
    name: "Cineclube",
    category: "Cinema",
    description: "Sessões de filmes clássicos, independentes e contemporâneos com discussão.",
    members: 267,
    image: "https://images.unsplash.com/photo-1489599849228-ed4dc3ee49b9?w=400&h=300&fit=crop",
    course: "Comunicação Social",
  },
  {
    id: 6,
    name: "Clube de Literatura",
    category: "Literatura",
    description: "Discussões sobre livros, autores e criação literária em ambiente colaborativo.",
    members: 178,
    image: "https://images.unsplash.com/photo-1507842217343-583f20270319?w=400&h=300&fit=crop",
    course: "Letras",
  },

  // Tecnologia
  {
    id: 7,
    name: "Clube de Programação",
    category: "Tecnologia",
    description: "Desenvolvedores se reunindo para aprender, colaborar e trabalhar em projetos.",
    members: 523,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    course: "Ciência da Computação",
  },
  {
    id: 8,
    name: "Clube de Web Development",
    category: "Tecnologia",
    description: "Especializado em desenvolvimento web moderno e frameworks atuais.",
    members: 234,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    course: "Ciência da Computação",
  },
  {
    id: 9,
    name: "Laboratório de IA",
    category: "Tecnologia",
    description: "Pesquisa e desenvolvimento em inteligência artificial e machine learning.",
    members: 156,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    course: "Ciência da Computação",
  },
  {
    id: 10,
    name: "Clube de Segurança da Informação",
    category: "Tecnologia",
    description: "Estudos sobre cibersegurança, proteção de dados e ethical hacking.",
    members: 145,
    image: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=300&fit=crop",
    course: "Ciência da Computação",
  },

  // Engenharias
  {
    id: 11,
    name: "Associação de Engenheiros Civis",
    category: "Engenharia",
    description: "Networking e discussões sobre construção, estruturas e projetos civis.",
    members: 198,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=300&fit=crop",
    course: "Engenharia Civil",
  },
  {
    id: 12,
    name: "Clube de Engenharia Elétrica",
    category: "Engenharia",
    description: "Projetos, pesquisas e estudos em engenharia elétrica e energia.",
    members: 167,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=300&fit=crop",
    course: "Engenharia Elétrica",
  },
  {
    id: 13,
    name: "Robótica e Automação",
    category: "Engenharia",
    description: "Desenvolvimento de projetos de robótica, drones e sistemas automatizados.",
    members: 289,
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=400&h=300&fit=crop",
    course: "Engenharia Mecânica",
  },

  // Saúde
  {
    id: 14,
    name: "Liga de Medicina Interna",
    category: "Saúde",
    description: "Estudos clínicos e discussão de casos de medicina interna.",
    members: 234,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop",
    course: "Medicina",
  },
  {
    id: 15,
    name: "Grupo de Pesquisa Clínica",
    category: "Saúde",
    description: "Desenvolvimento de pesquisas e projetos científicos na área de saúde.",
    members: 145,
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=300&fit=crop",
    course: "Medicina",
  },
  {
    id: 16,
    name: "Associação de Enfermagem",
    category: "Saúde",
    description: "Profissionalização e desenvolvimento em enfermagem clínica.",
    members: 178,
    image: "https://images.unsplash.com/photo-1631217314498-c5c189e9c0aa?w=400&h=300&fit=crop",
    course: "Enfermagem",
  },
  {
    id: 17,
    name: "Grupo de Psicologia Clínica",
    category: "Saúde",
    description: "Estudos de casos clínicos e discussão de práticas em psicologia.",
    members: 156,
    image: "https://images.unsplash.com/photo-1527482797697-8795b1a55a45?w=400&h=300&fit=crop",
    course: "Psicologia",
  },

  // Ciências Sociais
  {
    id: 18,
    name: "Clube de Direito",
    category: "Ciências Sociais",
    description: "Estudos jurídicos, debates sobre leis e políticas públicas.",
    members: 234,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
    course: "Direito",
  },
  {
    id: 19,
    name: "Grupo de Educadores",
    category: "Ciências Sociais",
    description: "Professores e futuros educadores compartilhando metodologias e práticas.",
    members: 167,
    image: "https://images.unsplash.com/photo-1427504494888-7d0ac21345fe?w=400&h=300&fit=crop",
    course: "Pedagogia",
  },
  {
    id: 20,
    name: "Associação de Administradores",
    category: "Ciências Sociais",
    description: "Desenvolvimento de liderança e gestão empresarial.",
    members: 289,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Administração",
  },

  // Comunicação
  {
    id: 21,
    name: "Agência de Publicidade Estudantil",
    category: "Comunicação",
    description: "Criação de campanhas publicitárias e projetos de comunicação.",
    members: 145,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Publicidade e Propaganda",
  },
  {
    id: 22,
    name: "Rádio Universitária",
    category: "Comunicação",
    description: "Produção de conteúdo de áudio e programas radiofônicos.",
    members: 98,
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=300&fit=crop",
    course: "Comunicação Social",
  },

  // Ciências Naturais
  {
    id: 23,
    name: "Grupo de Pesquisa em Agronomia",
    category: "Ciências Naturais",
    description: "Pesquisas e projetos em agricultura, sustentabilidade e agroecologia.",
    members: 123,
    image: "https://images.unsplash.com/photo-1574152611937-0df4b286107c?w=400&h=300&fit=crop",
    course: "Agronomia",
  },
  {
    id: 24,
    name: "Sociedade de Ciências",
    category: "Ciências Naturais",
    description: "Discussões sobre descobertas científicas e pesquisa experimental.",
    members: 189,
    image: "https://images.unsplash.com/photo-1574152611937-0df4b286107c?w=400&h=300&fit=crop",
    course: "Ciências Naturais",
  },

  // Geral
  {
    id: 25,
    name: "Grupo de Estudos",
    category: "Acadêmico",
    description: "Reuniões para estudar em grupo, trocar materiais e preparar para provas.",
    members: 412,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Multidisciplinar",
  },
  {
    id: 26,
    name: "Empresa Jr. Multidisciplinar",
    category: "Empreendedorismo",
    description: "Desenvolvimento de projetos e consultoria com estudantes de várias áreas.",
    members: 167,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Multidisciplinar",
  },
  {
    id: 27,
    name: "Grupo Ambiental",
    category: "Sustentabilidade",
    description: "Ações ambientais, reciclagem e conscientização sustentável.",
    members: 234,
    image: "https://images.unsplash.com/photo-1574152611937-0df4b286107c?w=400&h=300&fit=crop",
    course: "Multidisciplinar",
  },
  {
    id: 28,
    name: "Centro de Acessibilidade",
    category: "Inclusão",
    description: "Promotores de acessibilidade e inclusão para todos os estudantes.",
    members: 98,
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop",
    course: "Multidisciplinar",
  },
];
